repositories {
    // paper
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'paper-plugin.yml'
        expand(version: project.version)
    }
}

dependencies {
    // Compile
    compileOnly 'io.papermc.paper:paper-api:26.2.build.112-stable'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

shadowJar {
    relocate 'paper.platform', 'true'
}