import org.gradle.api.attributes.java.TargetJvmVersion

repositories {
    // paper
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'paper-plugin.yml'
        expand(version: project.version)
    }
}

configurations.all {
    if (canBeResolved) {
        attributes {
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 25)
        }
    }
}

dependencies {
    // Compile
    compileOnly 'io.papermc.paper:paper-api:26.2.build.112-stable'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

shadowJar {
    relocate 'paper.platform', 'true'
}